name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

env:
  DOCKER_API_VERSION: 1.48

jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        docker_version:
          - "29.0"
    runs-on: ubuntu-latest
    name: JVM (Docker v${{ matrix.docker_version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Prune Docker System
        run: docker system prune -a -f

      - name: Run Tests
        run: ./gradlew jvmTest
  native:
    if: ${{ vars.NATIVE_TESTS_ENABLED == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        docker_version:
          - "29.0"
        os:
          - name: linuxX64
            runner: ubuntu-22.04

          - name: macosX64
            runner: macos-15-intel
    runs-on: ${{ matrix.os.runner }}
    name: Native ${{ matrix.os.name }} (Docker v${{ matrix.docker_version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Docker
        uses: docker/setup-docker-action@v4.6.0
        if: ${{ matrix.os.name == 'macosX64' }}

      - name: Prune Docker System
        run: docker system prune -a -f

      - name: Run Tests
        run: ./gradlew ${{ matrix.os.name }}Test
